// test/smoke.test.mjs — boots this canvas's runtime over HTTP and exercises
// its actions. Generated by create-canvas-app. Run:  node test/smoke.test.mjs
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const home = await mkdtemp(join(tmpdir(), "agentic-kanban-smoke-"));
process.env.COPILOT_HOME = home;

const { canvasConfig } = await import("../canvas.mjs");
const { createCanvasRuntime } = await import("../canvas-kit/server.mjs");
const runtime = createCanvasRuntime(canvasConfig);

let passed = 0;
async function test(label, fn) {
  try {
    await fn();
    passed++;
    console.log(`  ok  ${label}`);
  } catch (e) {
    console.error(`FAIL  ${label}\n      ${e.message}`);
    process.exitCode = 1;
    throw e;
  }
}
const post = (url, actionName, input) =>
  fetch(new URL("/action", url), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ actionName, input }),
  }).then(async (r) => ({ status: r.status, body: await r.json() }));
const getState = (url) => fetch(new URL("/state", url)).then((r) => r.json());

try {
  const open = await runtime.openInstance({
    instanceId: "smoke",
    input: {},
    ctx: { instanceId: "smoke", input: {} },
  });
  await test("opens on a loopback url", () =>
    assert.match(open.url, /^http:\/\/127\.0\.0\.1:\d+\/$/));
  await test("GET /state starts with an empty board", async () => {
    const s = await getState(open.url);
    assert.deepEqual(s.cards, []);
  });

  let id;
  await test("add_card creates a backlog card", async () => {
    const { body } = await post(open.url, "add_card", {
      title: "Draft launch brief",
      assignee: "PM_USER",
    });
    assert.equal(body.ok, true);
    id = body.result.id;
    assert.ok(id);
    const s = await getState(open.url);
    assert.equal(s.cards.length, 1);
    assert.equal(s.cards[0].title, "Draft launch brief");
    assert.equal(s.cards[0].column, "backlog");
  });

  await test("assign_card changes the assignee", async () => {
    const { body } = await post(open.url, "assign_card", { id, assignee: "RISK_USER" });
    assert.equal(body.ok, true);
    const s = await getState(open.url);
    assert.equal(s.cards[0].assignee, "RISK_USER");
  });

  await test("move_card changes the workflow column", async () => {
    const { body } = await post(open.url, "move_card", { id, column: "review" });
    assert.equal(body.ok, true);
    const s = await getState(open.url);
    assert.equal(s.cards[0].column, "review");
  });

  await test("list_cards summarizes for the agent", async () => {
    const { body } = await post(open.url, "list_cards", {});
    assert.equal(body.result.count, 1);
    assert.match(body.result.summary, /Draft launch brief/);
  });

  await test("invalid columns are rejected before the handler", async () => {
    const result = await post(open.url, "move_card", { id, column: "blocked" });
    assert.equal(result.status, 400);
    assert.equal(result.body.code, "invalid_input");
  });

  await test("missing cards surface a handler error", async () => {
    const result = await post(open.url, "assign_card", {
      id: "missing",
      assignee: "PM_USER",
    });
    assert.equal(result.status, 500);
    assert.equal(result.body.ok, false);
    assert.match(result.body.message, /No card/);
  });
} finally {
  await runtime.shutdown();
  await rm(home, { recursive: true, force: true });
}

console.log(`\n${passed} checks passed`);
