"""The same agent loop, in LangChain.

Read this beside `agent_loop.py`. The loop is identical; what changes is who
does each job:

| Job | By hand (`agent_loop.py`) | LangChain |
|---|---|---|
| Tool schema | Written as JSON Schema | Generated by `@tool` from type hints; docstring becomes the description |
| Messages | Plain dicts with roles | `HumanMessage`, `AIMessage` (with `tool_calls`), `ToolMessage` |
| Argument checking | `jsonschema.validate` | The generated schema, checked when the tool is invoked |
| Structured answer | Parsing text yourself | `with_structured_output(Schema)` |
| Instrumentation hooks | Spans you write | Callback handlers, plus the same spans |

Governance, the spans, and the audit trail do **not** move into the
framework: they go through the same `governed_call`. A framework can make a
tool easy to call; deciding whether it may be called stays in your code.

The model is `ScriptedToolModel`. LangChain's `GenericFakeChatModel`
implements neither `bind_tools` nor `with_structured_output`; a subclass
whose `bind_tools` returns itself, fed `AIMessage`s that carry `tool_calls`,
supports both (checked against langchain-core in this repository).
"""

from __future__ import annotations

from collections.abc import Collection, Sequence
from pathlib import Path
from typing import Any

from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.language_models.fake_chat_models import GenericFakeChatModel
from langchain_core.messages import BaseMessage, HumanMessage, ToolMessage
from langchain_core.tools import BaseTool, tool
from pydantic import BaseModel, Field

from src.analytics.curves import interpolate_curve
from src.control.audit import current_trace_id
from src.foundations.agent_loop import (
    AGENT_NAME,
    DEMO_CURVE_RATES_PCT,
    DEMO_CURVE_TENORS,
    RunResult,
    governed_call,
    tracer,
)
from src.observability.telemetry import configure_telemetry


@tool
def interpolate_yield(target_tenor_years: float) -> float:
    """Interpolate the demo yield curve at one tenor in years (1 to 10).
    Returns a yield in percent."""
    return interpolate_curve(
        DEMO_CURVE_TENORS, DEMO_CURVE_RATES_PCT, [target_tenor_years]
    )[0]


@tool
def place_order(ticker: str, quantity: int) -> str:
    """Place a trade order."""
    raise AssertionError("place_order executed: governance failed")


class YieldAnswer(BaseModel):
    """A structured final answer, so code can use it without parsing prose."""

    tenor_years: float = Field(description="The tenor asked about, in years")
    yield_pct: float = Field(description="The interpolated yield, in percent")
    source: str = Field(description="Where the number came from")


class ScriptedToolModel(GenericFakeChatModel):
    """A fake chat model that accepts tools, so the tool-calling path and
    `with_structured_output` work offline."""

    def bind_tools(self, tools: Sequence[Any], **kwargs: Any) -> ScriptedToolModel:
        return self


class CallCounter(BaseCallbackHandler):
    """Callbacks are LangChain's instrumentation hook: the same place a
    tracing integration attaches. This one only counts."""

    def __init__(self) -> None:
        self.model_starts = 0
        self.model_ends = 0

    def on_chat_model_start(self, *args: Any, **kwargs: Any) -> None:
        self.model_starts += 1

    def on_llm_end(self, *args: Any, **kwargs: Any) -> None:
        self.model_ends += 1


def _as_dicts(messages: Sequence[BaseMessage]) -> list[dict[str, Any]]:
    """Normalise to the same transcript shape as part 1, so one grader works
    for both loops."""
    transcript = []
    for message in messages:
        entry: dict[str, Any] = {"role": message.type, "content": message.content}
        if getattr(message, "tool_calls", None):
            entry["tool_calls"] = [
                {"id": c["id"], "name": c["name"], "arguments": c["args"]}
                for c in message.tool_calls
            ]
        transcript.append(entry)
    return transcript


def run_langchain_agent(
    question: str,
    model: ScriptedToolModel,
    tools: Sequence[BaseTool],
    *,
    allowed_tools: Collection[str],
    audit_log: Path,
    max_steps: int = 5,
    callbacks: Sequence[BaseCallbackHandler] = (),
    identity: str = "learner",
    role: str = "RESEARCH_USER",
) -> RunResult:
    configure_telemetry()  # before the first span; see run_agent()
    by_name = {t.name: t for t in tools}
    bound = model.bind_tools([t for t in tools if t.name in allowed_tools])
    messages: list[BaseMessage] = [HumanMessage(question)]
    audit: list[dict[str, Any]] = []
    with tracer.start_as_current_span(f"invoke_agent {AGENT_NAME}") as run_span:
        run_span.set_attribute("gen_ai.operation.name", "invoke_agent")
        run_span.set_attribute("gen_ai.agent.name", AGENT_NAME)
        trace_id = current_trace_id()
        for _ in range(max_steps):
            with tracer.start_as_current_span("chat scripted-model") as span:
                span.set_attribute("gen_ai.operation.name", "chat")
                reply = bound.invoke(messages, config={"callbacks": list(callbacks)})
            messages.append(reply)
            if not reply.tool_calls:
                run_span.set_attribute("app.agent.stop_reason", "answered")
                return RunResult(
                    str(reply.content), "answered", _as_dicts(messages), trace_id, audit
                )
            for call in reply.tool_calls:
                target = by_name.get(call["name"])
                content = governed_call(
                    call["name"],
                    call["id"],
                    known=by_name,
                    allowed=allowed_tools,
                    run=lambda target=target, call=call: target.invoke(call["args"]),
                    audit_log=audit_log,
                    identity=identity,
                    role=role,
                    audit=audit,
                )
                messages.append(ToolMessage(content, tool_call_id=call["id"]))
        run_span.set_attribute("app.agent.stop_reason", "max_steps")
        return RunResult(None, "max_steps", _as_dicts(messages), trace_id, audit)


def structured_answer(model: ScriptedToolModel, prompt: str) -> YieldAnswer:
    """Ask for a typed answer instead of prose."""
    return model.with_structured_output(YieldAnswer).invoke(prompt)
